ch1/accounts/urls.py
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls import url
from django.conf import settings

urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.login, name="login"),
    url(r'^logout/$', auth_views.logout, name='logout',
        kwargs={'next_page': settings.LOGIN_URL}),
    url(r'^profile/$', views.profile, name="profile"),
]

ch1/mysite/urls.py
from django.contrib import admin
from django.conf.urls import url, include

# 미디어 설정
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns




urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^travel/', include('travel.urls', namespace='travel')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
]




# 미디어 업로드
# 어떤 URL을 정적으로 추가할래? > MEDIA_URL을 static 파일 경로로 추가
# 실제 파일은 어디에 있는데? > MEDIA_ROOT 경로내의 파일을 static 파일로 설정

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ch1/travel/urls.py
from django.conf.urls import url
from . import views




urlpatterns =[
    url(r'^$', views.main, name='main'),
    url(r'^local/$', views.local_list, name="local_list"),
    url(r'^local/(?P<City>\w+)/$', views.local_detail, name="local_detail"),
    url(r'^local/(?P<City>\w+)/(?P<pk>\d+)/$', views.local_detail_form, name='local_detail_form'),
    url(r'^new/$', views.post_new, name="post_new")
]

ch1/accounts/models.py
from django.conf import settings
from django.core.validators import RegexValidator
from django.db import models



class Profile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    phone_number = models.CharField(max_length=20, validators=[RegexValidator(r'^010[1-9]\d{7}$')])

ch1/travel/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse
from django.core.validators import MinValueValidator, MaxValueValidator


class TypeOfTour(models.Model):
    type = models.CharField(max_length=30)

    def __str__(self):
        return self.type

class Country(models.Model):
    country = models.CharField(max_length=20)

    def __str__(self):
        return self.country

class City(models.Model):
    country = models.ForeignKey(Country)
    city = models.CharField(max_length=15)

    def __str__(self):
        return self.city

class Language(models.Model):
    language = models.CharField(max_length=20)

    def __str__(self):
        return self.language

class Post(models.Model):
    name = models.CharField(max_length=20)
    # Basic Infomation
    title = models.CharField(max_length=30)
    Tourtype = models.ForeignKey(TypeOfTour)
    Country = models.ForeignKey(Country)
    City = models.ForeignKey(City)
    Language = models.ForeignKey(Language)
    DetailContent = models.CharField(max_length=1200)
    BriefContent = models.CharField(max_length=250)
    HashTag = models.CharField(max_length=20)
    img = models.ImageField()

    # Course Infomation
    MeetingPoint = models.CharField(max_length=50)
    MeetingTime = models.CharField(max_length=30)
    Map = models.CharField(max_length=10)
    Direction = models.CharField(max_length=200)
    CourseName = models.CharField(max_length=40)
    Duration = models.CharField(max_length=20)

    # Price & Other Information
    Price = models.CharField(max_length=10)
    Minimum = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(20)])
    Maximum = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(20)])
    Price_include = models.CharField(max_length=100)
    # 달력 구현원함
    NotDate = models.CharField(max_length=100)
    GuestInfo = models.CharField(max_length=100)

    # etc
    Created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('travel:local_detail_form', args=[self.City, self.name])

ch1/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from django.contrib.auth.forms import AuthenticationForm


class SignupForm(UserCreationForm):
    phone_number = forms.CharField()
    def save(self):
        user = super().save()
        profile = Profile.objects.create(user=user, phone_number=self.cleaned_data['phone_number'])
        return user

class LoginForm(AuthenticationForm):
    answer = forms.IntegerField(label='3+3=?')
    def clean_answer(self):
        if self.cleaned_data.get('answer', None) != 6:
            raise forms.ValidationError('땡~!!!')

ch1/travel/forms.py
from .models import Post
from django import forms



class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'Tourtype',
            'Country',
            'City',
            'Language',
            'DetailContent',
            'BriefContent',
            'HashTag',
            'MeetingPoint',
            'MeetingTime',
            'Map',
            'Direction',
            'CourseName',
            'Duration',
            'Price',
            'Minimum',
            'Maximum',
            'Price_include',
            'NotDate',
            'GuestInfo',
        ]

    def save(self, commit=True):
        post = Post(**self.cleaned_data)
        if commit:
            post.save()
        return post

ch1/accounts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from django.contrib.auth.views import login as auth_login
from allauth.socialaccount.models import SocialApp
from allauth.socialaccount.templatetags.socialaccount import get_providers
from .forms import LoginForm, SignupForm


def signup(request):
    if request.method =='POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect(settings.LOGIN_URL)
        else:
            form = SignupForm()
        return render(request, 'accounts/signup_form.html',{
            'form':form,
        })

def profile(request):
    return render(request, 'accounts/profile.html')



def login(request):
    providers = []
    for provider in get_providers():     # settings/INSTALLED_APPS 내에서 활성화된 목록
        # social_app속성은 provider에는 없는 속성입니다.
        try:
            # 실제 Provider 별 Client id/secret 이 등록이 되어있는가?
            provider.social_app = SocialApp.objects.get(provider=provider.id, sites=settings.SITE_ID)
        except SocialApp.DoesNotExist:
            provider.social_app = None
        providers.append(provider)

    return auth_login(request,
        authentication_form=LoginForm,
        template_name=['accounts/login_form.html','mystie/base.html'],
        extra_context={'providers': providers})

ch1/travel/views.py
from django.shortcuts import render, redirect
from .models import Post,City
from .forms import PostForm


def main(request):
    return render(request, 'travel/_main.html')

def local_list(request):
    queryset = City.objects.all()

    queryset1 = Post.objects.all()


    return render(request, 'travel/local_list.html', {
        'local' : queryset,
        'local_list' : queryset1
    })

def local_detail(request, City):
    queryset = Post.objects.all()
    path = request.path
    print(path)
    filter = path.split('/')[3]
    print(filter)
    qs = queryset.filter(City__city=filter)

    return render(request, 'travel/local_detail.html',{
        'local_list': qs
    })


def local_detail_form(request, City ,pk):
    queryset = Post.objects.all()
    path = request.path
    print(path)
    filter = path.split('/')[4]
    print(filter)
    qs = queryset.filter(pk=filter)
    return render(request, 'travel/local_detail_form.html',{
        'local_detail': qs,
        'filter':filter,
    })



def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            return redirect(post)
    else:
        form = PostForm()
    return render(request, 'travel/post_form.html', {
        'form': form,
})

ch1/accounts/templates/accounts/login_form.html
{% extends "base.html" %}

{% block content %}
{% load socialaccount %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" />
</form>
<h3>Social Login</h3>
<ul>
    {% for provider in providers %}
        <li>
            {% if provider.social_app %}
                <a href="{% provider_login_url provider.id %}">
                    {{ provider.name }}
                </a>
            {% else %}
                <a>
                    Provider {{ provider.name }} 설정이 필요합니다.
                </a>
            {% endif %}
        </li>
    {% endfor %}
 </ul>
 {% endblock %}

ch1/accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block content %}
<link rel="stylesheet"
      href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
<h1>{{ user }}'s Profile</h1>
<ul>
    <li>email : {{ user.email }}</li>
    <li>name : {{ user.name }}</li>
    <li>date_joined : {{ user.date_joined }}</li>
</ul>
<img src="{{ user.socialaccount_set.all.first.get_avatar_url }}" />

<a href="{% url 'travel:post_new' %}"><h2>가이드로 등록하기</h2> </a>

{% endblock %}

ch1/mysite/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Today's Friend</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width", initial-scale="1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
</head>
<body>
    <!-- navbar_top -->
    <style>
        .navbar-default{
            background-color: #0F3A72;
        }
        .container-fluid  ul  li{
            color: white;
        }

        @media (min-width: 768px){
            /* 큰 화면 전용 설정 */
            .container-fluid{
                padding:0 20%;
            }
            .fcontent {
                padding:0 20%;
                display: flex;
            }
        }
        @media (max-width: 786px) {
            .fcontent{
                display:flex;
            }
        }
        #login-dp{
            min-width: 250px;
            padding: 14px 14px 0;
            overflow:hidden;
            background-color:rgba(255,255,255,.8);
        }
        #login-dp .help-block{
            font-size:12px    
        }
        #login-dp .bottom{
            background-color:rgba(255,255,255,.8);
            border-top:1px solid #ddd;
            clear:both;
            padding:14px;
        }
        #login-dp .social-buttons{
            margin:12px 0    
        }
        #login-dp .social-buttons a{
            width: 49%;
        }
        #login-dp .form-group {
            margin-bottom: 10px;
        }
        .btn-fb{
            color: #fff;
            background-color:#3b5998;
        }
        .btn-fb:hover{
            color: #fff;
            background-color:#496ebc 
        }
        .btn-tw{
            color: #fff;
            background-color:#55acee;
        }
        .btn-tw:hover{
            color: #fff;
            background-color:#59b5fa;
        }
        @media(max-width:768px){
            #login-dp{
                background-color: inherit;
                color: #fff;
            }
            #login-dp .bottom{
                background-color: inherit;
                border-top:0 none;
            }
        }
    </style>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button style="border:2px solid #333333;" type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#list" aria-expanded="false">
                    <span class="sr-only"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'travel:main' %}">Today's Friend</a>
            </div>
            <div class="collapse navbar-collapse" id="list">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href=#>Laguage</a></li>
                    <li><a href="{% url 'travel:local_list' %}">Tour</a></li>
                    <li><a href="{% url 'travel:post_new' %}">Become a guide</a></li>
                    <ul class="nav navbar-nav navbar-right">
                            <li><p class="navbar-text">Already have an account?</p></li>
                            <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>
                                <ul id="login-dp" class="dropdown-menu">
                                    <li>
                                         <div class="row">
                                                <div class="col-md-12">
                                                    Login via
                                                    <div class="social-buttons">
                                                        <a href="#" class="btn btn-fb"><i class="fa fa-facebook"></i> Facebook</a>
                                                        <a href="#" class="btn btn-tw"><i class="fa fa-twitter"></i> Twitter</a>
                                                        <form action="" method="post">
                                                            {% csrf_token %}
                                                            <table>
                                                                {{ form.as_table }}
                                                            </table>
                                                            <input type="submit" />
                                                        </form>
                                                    </div>
                                                    or
                                                     <form class="form" role="form" method="post" action="login" accept-charset="UTF-8" id="login-nav">
                                                            {% csrf_token %}
                                                            <table>
                                                                {{ form.as_table }}
                                                            </table>
                                                            <input type="submit" />
                                                            <div class="form-group">
                                                                 <label class="sr-only" for="exampleInputEmail2">Email address</label>
                                                                 <input type="email" class="form-control" id="exampleInputEmail2" placeholder="Email address" required>
                                                            </div>
                                                            <div class="form-group">
                                                                 <label class="sr-only" for="exampleInputPassword2">Password</label>
                                                                 <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Password" required>
                                                                 <div class="help-block text-right"><a href="">Forget the password ?</a></div>
                                                            </div>
                                                            <div class="form-group">
                                                                 <button type="submit" class="btn btn-primary btn-block">Sign in</button>
                                                            </div>
                                                            <div class="checkbox">
                                                                 <label>
                                                                 <input type="checkbox"> keep me logged-in
                                                                 </label>
                                                            </div>
                                                     </form>
                                                </div>
                                                <div class="bottom text-center">
                                                    New here ? <a href="#"><b>Join Us</b></a>
                                                </div>
                                         </div>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                </ul>
            </div>
        </div>
    </nav>
    <div style="height:50px;"></div>
    {% block content %}
    {% endblock %}
    <footer style="background-color:rgb(187, 184, 184)">
        <div class="container">
            <br>
            <div class="row" style="margin:0 auto">
                <p class="text-center">
                    회사소개 &nbsp; |&emsp;
                    이용약관 &nbsp; |&emsp;
                    개인정보 처리방침 &nbsp; |&emsp;
                    위치기반 서비스 이용약관 &nbsp; |&emsp;
                    중개사 사이트 바로가기
                </p>
            </div>
            <br>
            <p class="text-center">상호 : Tryground&emsp; 대표 : 김희인 &emsp;주소: 경기도 광명시 소하동 1391-4번지(14328)</p>
            <p class="text-center">서비스 이용문의 : 010-5016-1069 &emsp;&emsp;이메일 : gmldls420@naver.com </p>
            <br>
            <br>
            <p class="text-center">
                Copyright @ Tryground. All Right Reserved.
            </p>
        </div>
    </footer>
{% load static %}
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

ch1/mysite/templates/home.html
{% extends "base.html" %}

{% block content %}
<h1>1111</h1>
{% endblock %}

ch1/travel/templates/travel/Untitled-1.html
<div class="col-sm-12 col-md-9 nopadding">
    <div class="cruise-list listing-style3 cruise">
        <article class="box" style='background:#fed'>
	<a href="budapest/the-backpacker-pubcrawl-budapest">
		<div class="col-md-12">
			<h6 style="border-bottom:1px dotted #fba749;color:#fba749;font-weight:bold;font-size:76%;padding-bottom:8px;margin-bottom:8px;margin-top:-7px;">Featured tour</h6>
		</div>
		<figure class="col-sm-3 col-xs-5">
			<img src="https://admin.freetour.com/images/tours/5/the-backpacker-pubcrawl---budapest-01.jpg" style='max-height:140px'/>
			<div style='text-align:center;background:#fff;padding:3px 10px'>Night life</div>
			<div style='position: absolute;top: 15px;color:#fff;font-weight:bold;' class='hidden-xs'><span style='background:#fba749;margin-left:-15px;padding:2px 2px 2px 15px;'>VERY POPULAR</span><span style='background:transparent url("/images/corner stuff orange-04.png") no-repeat;width: 10px;display: inline-block;height:20px;float: right'></span></div>
		</figure>
		<div class="details result col-sm-9 col-xs-7">
		    <div class="clearfix row">
			    <h4 class="box-title col-xs-9">Pub Crawl Budapest
				    <img data-toggle="tooltip" data-placement="right" id='rec-tour-image' src='/images/thumb-recommended2.png' title='This tour is recommended by FREETOUR.com based on the feedback we have often received from travelers.' style='cursor:help'/>
				    <small>Provided by The Backpacker Pubcrawl</small>
				    <div style='color:#fff;font-weight:bold;background:#fba749' class='hide-sm hidden-md hidden-lg'>VERY POPULAR</div>
				</h4>
				<span class="price col-xs-3">
					&euro;12<small style='color:#1b4e8b'>Discount available</small>
				</span>
			</div>

		<div class="clearfix mtop">
			<div class='review' style='height:58px'>
				Budapest is known worldwide for it’s electric nightlife. Home to the unique and wonderfully odd ruin bars, insane nightclubs and bars that never close. 
			</div>
		</div>
			<div class="character  badged " style='float:left;margin-top:10px'>
				<div class="col-md-5 col-sm-12 col-xs-12 cruise-logo">
				    <div>
						<span style='display:inline-block;border:1px solid transparent;padding:3px 5px;float:left;margin:5px 7px 5px 0px;background:#fba749;color:#fff;border-radius: 3px;font-weight:bold'>8.6</span>
						<span class="dark-blue-color ">Rating</span><br/><span><i class="fa fa-comment-o"></i> 42</span>
					</div>
				</div>
				<div class="col-md-5 hide-sm cruise-logo hide-mob">
					<div>
						<span class="dark-blue-color ">Languages</span><br>English
                    </div>
				</div>
				<div class="col-md-2 hide-sm cruise-logo hide-mob">
					<div>
						<span class="dark-blue-color ">Duration</span><br>5:00
					</div>
				</div>
				<div style="clear:both"></div>
			</div>
			<button class="button btn-small pull-right hide-mob">Details</button>
		</div>
	</a>
</article>
</div>
</div>

ch1/travel/templates/travel/_main.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<video preload="auto" id="bgvid" loop width="100%" muted="muted" autoplay="true">
    <source src="{% static 'video/main.mp4' %}" type="video/mp4">
</video>

<div class="jumbotron">
    <div class="container">
        <div class="row">
            <div class="col-md-4" style="margin-top:15px;">
                <a href="/travel/local/Seoul"><img src="{% static 'img/상품지역/Seoul1.jpg' %}" style="max-height:200px; width:380px;"></a>
            </div>
            <div class="col-md-4" style="margin-top:15px;">
                <a href="/travel/local/Seoul"><img src="{% static 'img/상품지역/Seoul2.jpg' %}" style="max-height: 200px; background-attachment:fixed; width:380px;"></a>
            </div>
            <div class="col-md-4" style="margin-top:15px;">
                    <a href="/travel/local/Jeju"><img src="{% static 'img/상품지역/Jeju.jpg' %}" style="max-height:200px; width:380px;"></a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4" style="margin-top:15px;">
                <a href="/travel/local/Busan"><img src="{% static 'img/상품지역/Busan.jpg' %}" style="max-height:200px; width:380px;"></a>
            </div>
            <div class="col-md-4" style="margin-top:15px;">
                <a href="/travel/local/Gyeongju"><img src="{% static 'img/상품지역/Gyeongju.JPG' %}" style="max-height: 200px; width:380px;"></a>
            </div>
            <div class="col-md-4" style="margin-top:15px;">
                    <a href="/travel/local/Jeonju"><img src="{% static 'img/상품지역/Jeonju.jpg' %}" style="max-height: 200px; width:380px;"></a>
                </div>
        </div>
    </div>
</div>

{% endblock %}

ch1/travel/templates/travel/local_detail.html
{% extends "base.html" %}

{% block content %}

<body>

    {% for i in local_list %}
    
        <div class="container">
            <div class="col-md-3">

            </div>
            <div class="col-md-9">
            <div class="well clearfix" style="background-color:rgb(243,243,243); margin:15px auto; padding:10px;">
                <article class="box">
                    <a href="{% url 'travel:local_detail_form' i.City i.pk %}">
                        <figure class="col-sm-3 col-xs-5">
                            <img src="{{ i.img.url }}" style="max-height:140px; width:100%">
                            <div style="text-align:center; background:#fff;padding:3px 10px">{{ i.Tourtype }}</div>
                        </figure>
                        <div class="detail result col-sm-9 col-xs-7">
                            <div class="clearfix row">
                                <h4 class="box-title col-xs-10">
                                      {{ i.title }}  <br>
                                    <small>Provided by Generaion {{ i.name }}</small>
                                </h4>
                                <span class="price col-xs-2">
                                    <small>from </small>{{ i.Price }}<br>
                                    <small>Tip based</small>
                                </span>
                            </div>
                        </div>
                        <div class="detail result col-sm-7 col-xs-4" style="height:58px">
                            {{ i.BriefContent }}
                        </div>
                        <div class="col-sm-3"># {{i.HashTag}}</div>
                    </a>
                </article>
            </div>
            </div>
        </div>
    </div>
    {% endfor %}

</body>
</html>

{% endblock %}

ch1/travel/templates/travel/local_detail_form.html
{% extends "base.html" %}

{% block content %}
{% for i in local_detail %}

<div class="container">
    <div class="jumbotron clearfix" style="margin-top:50px;">
        <div class="col-md-7">
            <p>title : {{ i.title }}<br>name: {{i.name}}<br>price : {{ i.Price }}<br>time : {{ i.Duration }}<br>Tour Local : {{ i.City }} <br>Enable Language : {{ i.Language }}<br>Visited_country : {{ i.Visited_country }} <br>Next_country : {{ i.next_country }}<br>Interest : {{i.interest}} <br> Content : {{ i.contet }}<br> Guide at: {{i.guide_at}}<br>Email : {{i.email }}</p>
        </div>
        <div class="col-md-5">
            <a href="#" class="btn btn-primary" style="margin:30px 0;width:333px; height:120px"><h1 class="text-center">book now</h1></a>
        </div>
    </div>
    
</div>

{% endfor %}
{% endblock %}

ch1/travel/templates/travel/local_list.html
{% extends "base.html" %}

{% block content %}
{% load static %}

<img src="{% static 'img/top.jpg' %}" width="100%" height="300">

<div class="jumbotron">

</div>



<div class="container">
    <div class="center-block" style="width:67.2%; margin-bottom:7px;">
        <a href="/travel/local/Seoul"><img src="{% static 'img/상품지역/Seoul1.jpg' %}" style="max-height:200px; width:380px;"></a>
        <a href="/travel/local/Seoul"><img src="{% static 'img/상품지역/Seoul2.jpg' %}" style="max-height: 200px; background-attachment:fixed; width:380px;"></a>
    </div>
    <div class="center-block" style="width:67.2%; margin-bottom:7px;">
        <a href="/travel/local/Busan"><img src="{% static 'img/상품지역/Busan.jpg' %}" style="max-height:200px; width:380px;"></a>
        <a href="/travel/local/Gyeongju"><img src="{% static 'img/상품지역/Gyeongju.JPG' %}" style="max-height: 200px; width:380px;"></a>
    </div>
    <div class="center-block" style="width:67.2%; margin-bottom:7px;">
        <a href="/travel/local/Jeju"><img src="{% static 'img/상품지역/Jeju.jpg' %}" style="max-height:200px; width:380px;"></a>
        <a href="/travel/local/Jeonju"><img src="{% static 'img/상품지역/Jeonju.jpg' %}" style="max-height: 200px; width:380px;"></a>
    </div>
</div>

<div class="container">
        <h2 class="text-center"></h2>
    </div>

{% endblock %}

ch1/travel/templates/travel/post_form.html
{% extends 'base.html' %}



{% block content %}

<link rel="stylesheet"
      href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />


<div class="container">
    <div style="border:1px solid gray; margin-top:40px;">
        <h2 style="margin-left:20px;">Create a Product</h2>
        <div style="border-top:1px solid gray; border-bottom:1px solid gray">
            <h2 style="margin-left:20px;">Basic Information</h2>
        </div>
        <div class="container" style="padding:30px;">
            <div class="row">
                <div class="col-md-3">
                    Name of tour
                    <br>
                    <input style="width:100%" type = "text" name = "{{ form.title.name }}" id="{{ form.title.id_for_label }}">
                </div>
                <div class="col-md-6">
                    Type of tour
                    <br>
                    {{ form.Tourtype }}
                </div>
            </div>
                    <br>
                    <br>
                    Country
                    <br>
                    {{ form.Country }}
                    {{ form.City }}
            </div>
                <div class="col-md-6">
                    <div class="col-md-6">Type of tour<br><input type = "text" name = "{{ form.Tourtype.name }}" id="{{ form.Tourtype.id_for_label }}"></div>
                    <div class="col-md-6"></div>
                </div>
                <div class="col-md-12"></div>
            </div>
        </div>

<script>
/* ??????? user_agent ??? ???? */
var dom = document.getElementById('{{ form.user_agent.id_for_label }}'); dom.value = navigator.userAgent;
</script>

{% endblock %}